import Head from 'next/head'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {selectCharState, setCharState} from "@/state/character.slice";
import {useDispatch, useSelector} from "react-redux";
import {CharAppearance} from "@/components/charcater/character";
import {CharPropreties} from "@/components/CharPropreties/CharPropreties";


const inter = Inter({subsets: ['latin']})

export default function Home() {

    const charState = useSelector(selectCharState);
    const dispatch = useDispatch();


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <CharAppearance/>
                <CharPropreties/>
            </main>
        </>
    )
}
