import Head from 'next/head'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {CharAppearance} from "@/components/charImg/charImg";
import {CharProperties} from "@/components/CharPropreties/CharProperties";
import {GeneralInfo} from "@/components/generalInfo/generalInfo/generalInfo";
import './../i18n'
import {LangSwitcher} from "@/components/langSwitcher/langSwitcher";

const inter = Inter({subsets: ['latin']})

export default function Home() {

    return (
        <>
            <Head>
                <title>Edit Character</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <LangSwitcher/>
                <GeneralInfo/>
                <CharAppearance/>
                <CharProperties/>
            </main>
        </>
    )
}
